- name: Install Golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Setup App Content
  ansible.builtin.import_tasks: app_presetup.yml

- name: Build Go Application
  ansible.builtin.shell: go mod init {{ component }} ; go get ; go build
  args:
    chdir: /app

- name: Setup Systemd Service
  ansible.builtin.import_tasks: systemd_setup.yml